.TH XOAT 1 "" 
.SH NAME
.PP
xoat - X11 Obstinate Asymmetric Tiler
.SH SYNOPSIS
.PP
\f[B]xoat\f[]
.SH DESCRIPTION
.PP
A static tiling window manager.
.PP
License: MIT/X11
.SH USAGE
.PP
See config.h for customization.
.PP
These are the default key bindings:
.TP
.B Mod4-1
Focus tile 1.
.RS
.RE
.TP
.B Mod4-2
Focus tile 2.
.RS
.RE
.TP
.B Mod4-3
Focus tile 3.
.RS
.RE
.TP
.B Shift-Mod4-1
Move window to tile 1.
.RS
.RE
.TP
.B Shift-Mod4-2
Move window to tile 2.
.RS
.RE
.TP
.B Shift-Mod4-3
Move window to tile 3.
.RS
.RE
.TP
.B Mod4-Tab
Flip top two windows in a tile.
.RS
.RE
.TP
.B Mod4-` (grave)
Cycle all windows in a tile.
.RS
.RE
.TP
.B Mod4-Escape
Close a window.
.RS
.RE
.TP
.B Mod4-f
Toggle state fullscreen.
While in fullscreen mode, an window is considered to be in tile 1.
.RS
.RE
.TP
.B Mod4-a
Toggle state above (only placed above fullscreen windows).
.RS
.RE
.TP
.B Mod4-Right
Focus next monitor.
.RS
.RE
.TP
.B Mod4-Left
Focus previous monitor.
.RS
.RE
.TP
.B Shift-Mod4-Right
Move window to next monitor.
.RS
.RE
.TP
.B Shift-Mod4-Left
Move window to previous monitor.
.RS
.RE
.TP
.B Shift-Mod4-x
Launch dmenu_run
.RS
.RE
.TP
.B F1
Launch urxvt
.RS
.RE
.TP
.B Mod4-F1
Raise windows in tag 1.
.RS
.RE
.TP
.B Shift-Mod4-F1
Place current window in tag 1.
.RS
.RE
.TP
.B Shift-Control-Mod4-F1
Remove current window from tag 1.
.RS
.RE
.TP
.B Mod4-F2
Raise windows in tag 2.
.RS
.RE
.TP
.B Shift-Mod4-F2
Place current window in tag 2.
.RS
.RE
.TP
.B Shift-Control-Mod4-F2
Remove current window from tag 2.
.RS
.RE
.TP
.B Mod4-F3
Raise windows in tag 3.
.RS
.RE
.TP
.B Shift-Mod4-F3
Place current window in tag 3.
.RS
.RE
.TP
.B Shift-Control-Mod4-F3
Remove current window from tag 3.
.RS
.RE
.SH OPTIONS
.PP
All configuration is done via config.h.
.PP
The xoat binary may be used to send messages to a running instance of
xoat.
They include:
.TP
.B xoat exit
Exit the window manager.
.RS
.RE
.TP
.B xoat restart
Restart the window manager in place without affecting the X session.
.RS
.RE
.SH SEE ALSO
.PP
\f[B]dmenu\f[] (1)
.SH AUTHOR
.PP
Sean Pringle <sean.pringle@gmail.com>
