.TH XOAT 1 "" 
.SH NAME
.PP
xoat - X11 Obstinate Asymmetric Tiler
.SH SYNOPSIS
.PP
\f[B]xoat\f[] [restart] [exit]
.SH DESCRIPTION
.PP
A static tiling window manager.
.PP
License: MIT/X11
.SH USAGE
.PP
See config.h for customization.
.PP
These are the default key bindings:
.TP
.B Mod4-Left
Focus tile 1.
.RS
.RE
.TP
.B Mod4-Right (and Up)
Focus tile 2.
.RS
.RE
.TP
.B Mod4-Down
Focus tile 3.
.RS
.RE
.TP
.B Shift-Mod4-Left
Move window to tile 1.
.RS
.RE
.TP
.B Shift-Mod4-Right (and Up)
Move window to tile 2.
.RS
.RE
.TP
.B Shift-Mod4-Down
Move window to tile 3.
.RS
.RE
.TP
.B Mod4-Tab
Flip top two windows in a tile.
.RS
.RE
.TP
.B Mod4-` (grave)
Cycle all windows in a tile.
.RS
.RE
.TP
.B Mod4-Escape
Close a window.
.RS
.RE
.TP
.B Mod4-f
Toggle state fullscreen.
While in fullscreen mode, an window is considered to be in tile 1.
.RS
.RE
.TP
.B Mod4-a
Toggle state above (only placed above fullscreen windows).
.RS
.RE
.TP
.B Mod4-Next (Page Down)
Focus next monitor.
.RS
.RE
.TP
.B Mod4-Prior (Page Up)
Focus previous monitor.
.RS
.RE
.TP
.B Shift-Mod4-Next
Move window to next monitor.
.RS
.RE
.TP
.B Shift-Mod4-Prior
Move window to previous monitor.
.RS
.RE
.TP
.B Shift-Mod4-x
Launch dmenu_run
.RS
.RE
.TP
.B F1
Launch urxvt
.RS
.RE
.TP
.B Mod4-s
Snapshot current window positions and stacking order.
.RS
.RE
.TP
.B Mod4-r
Rollback to snapshot.
Windows closed since the snapshot will not be reopened.
Newer windows not in the snapshot will be lowered.
.RS
.RE
.SH OPTIONS
.PP
All configuration is done via config.h.
.PP
The xoat binary may be used to send messages to a running instance of
xoat.
They include:
.TP
.B xoat exit
Exit the window manager.
.RS
.RE
.TP
.B xoat restart
Restart the window manager in place without affecting the X session.
.RS
.RE
.SH SEE ALSO
.PP
\f[B]dmenu\f[] (1)
.SH AUTHOR
.PP
Sean Pringle <sean.pringle@gmail.com>
